@host = http://localhost:3000/api/v1/auth
@contentType = application/json
@userAccessToken = {{$dotenv USER_ACCESS_TOKEN}}

###
POST {{host}}/sign-up
Content-Type: {{contentType}}

{
    "firstName": "Le",
    "lastName": "Xuan Hoa",
    "gender": true,
    "email": "training.dso.xuanhoa@gmail.com",
    "password": "dsoFresherXuanHoa",
    "roleId": 2
}

###
PATCH {{host}}/activation?activationCode=9a5e0b5a-a334-4622-af2e-a65adb2d2482
Content-Type: {{contentType}}

###
POST {{host}}/sign-in
Content-Type: {{contentType}}

{
    "email": "dso.intern.xuanhoa@gmail.com",
    "password": "dsoInternXuanHoa"
}

###
GET {{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}

###
PATCH {{host}}/reset-password?resetCode=9a5e0b5a-a334-4622-af2e-a65adb2d2482
Content-Type: {{contentType}}

{
    "password": "dsoInternXuanHoa"
}


###
GET {{host}}/reset-password?email=dso.intern.xuanhoa@gmail.com
Content-Type: {{contentType}}