@host = http://localhost:3000/api/v1/auth
@contentType = application/json
@userAccessToken = {{$dotenv USER_ACCESS_TOKEN}}
@adminAccessToken = {{$dotenv ADMIN_ACCESS_TOKEN}}

###
PATCH {{host}}/activation?activationCode=ee20c869-fa8c-43ae-926f-f783fcb1d411
Content-Type: {{contentType}}

###
POST {{host}}/sign-in
Content-Type: {{contentType}}

{
    "email": "dso.intern.xuanhoa@gmail.com",
    "password":"dsoInternXuanHoa"
}

###
GET {{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}

###
GET {{host}}/reset-password/?email=dso.intern.xuanhoa@gmail.com
Content-Type: {{contentType}}

###
PATCH {{host}}/reset-password/?resetCode=ee20c869-fa8c-43ae-926f-f783fcb1d411
Content-Type: {{contentType}}

{
    "password": "dsoInternXuanHoa"
}