@host = http://localhost:3000/api/v1/auth
@contentType = application/json
@userAccessToken = {{$dotenv USER_ACCESS_TOKEN}}
@adminAccessToken = {{$dotenv ADMIN_ACCESS_TOKEN}}

###
PATCH {{host}}/activation?activationCode=05e576c0-b447-4b26-a552-f7292d86cb5
Content-Type: {{contentType}}

###
POST {{host}}/sign-in
Content-Type: {{contentType}}

{
    "email": "training.dso.xuanhoa@gmail.com",
    "password":"dsoInternXuanHoa"
}

###
GET {{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{adminAccessToken}}

###
GET {{host}}/reset-password/?email=training.dso.xuanhoa@gmail.com
Content-Type: {{contentType}}

###
PATCH {{host}}/reset-password/?resetCode=05e576c0-b447-4b26-a552-f7292d86cb54
Content-Type: {{contentType}}

{
    "password": "dsoInternXuanHoa"
}

###
GET {{host}}/sign-out
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}