@host = http://localhost:3000/api/v1/qrcodes
@contentType = application/json
@userAccessToken = {{$dotenv USER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}

{
    "content": "Le Xuan Hoa",
    "background": "#ffffff",
    "foreground": "#000000",
    "borderWidth": 10,
    "ErrorLevel": 1,
    "circleShape": true
}

###
GET {{host}}/3eeb07b4-007a-4c68-a15d-857fb63b916a
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}

###
GET {{host}}/?page=1&size=3&startTime=1699429902&endTime=1699516302&version=3&errorLevel=2
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}