@host = http://localhost:3000/api/v1/users
@contentType = application/json
@userAccessToken = {{$dotenv USER_ACCESS_TOKEN}}

###
GET {{host}}/1/qrcodes/?page=1&size=2&startTime=1699381765&endTime=1699554565
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}